### ISSUE TITLE
defaultView 

### ISSUE THREAD

**Issue by alikahwaji** [StickNitro/ngx-fullcalendar#1]
Can I use 'timelineDay' as my defaultView?

**Comment by StickNitro** [comment]
Yes you can, however, you will need to purchase a license key for Schedule from [FullCalendar](https://fullcalendar.io/scheduler/purchase) and provide the key in the options otherwise you will be using the trial.

**Comment by Wello86** [comment]
What about adding day-week-month, how to do it, only month and listWeek works with me ?
