### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by SlimenTN** [StickNitro/ngx-fullcalendar#15]
**Describe the bug**
When I try to drag and drop the event within the calendar I get this error:
`Cannot read property 'id' of undefined`

**To Reproduce**
What I did is :
1- prepare a simple event in my-component.ts like so:
```javascript
  calendarOptions: FullCalendarOptions;
  events: EventObject[];
  constructor() { }

  ngOnInit() {
    this.calendarOptions = {
      titleFormat: 'DD MMMM YYYY',
      defaultDate: '2019-02-26',
      editable: true,
    };

    this.events = [
      { id: 2, title: 'Friends coming round', start: '2019-02-26T18:00:00', end: '2019-02-26T23:00:00' }
    ]
  }
```
2- call the calendar component inside my-component.html:

```html
<ngx-fullcalendar 
    defaultView="month"
    [options]="calendarOptions"
    [events]="events">
  </ngx-fullcalendar>
```

**Expected behavior**
Should drag and drop the event without any problem

**Screenshots**
when I dropped that event I got the following error:

![](https://i.ibb.co/ByYgdCM/Screen-Shot-2019-02-26-at-10-41-06-AM.png)

**Comment by StickNitro** [comment]
fixed in branch upgrade-v4-alpha
